-- Don't use!

SELECT 
    OTHER_DATA.FIRST_NAME, 
    OTHER_DATA.LAST_NAME, 
    OTHER_DATA.DESIGNATION, 
    LPAD(bogus_data.EMPLOYEE_ID, 7, '0') AS PADDED_EMPID
FROM 
    bogus_data AS OTHER_DATA
JOIN 
    bogus_data ON OTHER_DATA.EMPLOYEE_ID = bogus_data.EMPLOYEE_ID;
